# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'WJQ_ApeTravel' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
   pod 'SDWebImage', '~> 3.8.2'
  # Pods for WJQ_ApeTravel
pod 'SDiPhoneVersion', '~> 1.1.2'
   pod 'AFNetworking', '~> 3.1.0'
  target 'WJQ_ApeTravelTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
